name: Deploy to DigitalOcean

on:
  push:
    branches:
      - TS

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    # defaults:
    #   run:
    #     working-directory: /home/c0dy/app/

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: SSH into DigitalOcean server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: sh deploy.sh
